### ISSUE TITLE
Why does Authentik need a ClusterRole?

### ISSUE THREAD

**Issue by jacksgt** [goauthentik/helm#140]
Hi!

Thanks for providing this nice chart!

I was working on setting up Authentik in a multi-tenant environment and realized that this chart grants the "authentik" user *A LOT* of privileges in the cluster.
Specifically, the included ClusterRole grants permissions to read/modify/delete **ALL** secrets/deployments/ingresses in the *entire* cluster:
https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/rbac.yaml#L30

Could someone explain why this is necessary?
As far as I can tell, Authentik only needs to be able to manage these in its own namespace (for managing the outpost deployments).

**Comment by jacksgt** [comment]
The remote cluster variant has a (namespace-scoped) Role (not ClusterRole), so the same should be possible with the regular Authentik chart: https://github.com/goauthentik/helm/blob/main/charts/authentik-remote-cluster/templates/role.yaml

**Comment by BeryJu** [comment]
This isn't required and can be disabled without impacting anything. The reason the chart uses a ClusterRole by default is that authentik can create outposts in any namespace (since the namespace is configured within authentik)

The other reason is that for things like `customresourcedefinitions` as they are non-namespaced, a Cluster Role is required (and yeah of course that doesn't justify the ClusterRole being for everything)

I started work a while ago to remove this RBAC from this helm chart and instead use the remote-cluster chart as a subchart in this, but I haven't gotten around to finishing that
