### ISSUE TITLE
FR: Allow at least two ingresses to be created from chart

### ISSUE THREAD

**Issue by samip5** [goauthentik/helm#209]
I would love if it chart supported more than single ingress to be deployed as I need one external and one internal. :)

(I know I can do it outside the chart, but..)

**Comment by rissson** [comment]
I'll probably add an `extraResources` value with 2024.1 which will allow that kind of use cases.

**Comment by samip5** [comment]
@rissson I don't really see how this would help, as I also need the outpost to generate two without having manually done it?

**Comment by rissson** [comment]
So for outposts, as that's done by authentik, you'd still need to create the additional ingress manually anyway, which you can do with the changes from #230.

**Comment by samip5** [comment]
> additional ingress manually anyway,

Which should be supported from inside Authentik when configuring the outpost, which it's not so all changes to the domains need to be manually done.

**Comment by rissson** [comment]
That is indeed not supported currently. You can work around this by creating a new notification rule and associate a policy to it. In that policy, you can write Python, so you can create/update/delete ingresses as needed. [Here](https://gitlab.com/lama-corp/infra/infrastructure/-/blob/d57c0dbcc965e104579f87b287f4e83d8051ceb1/k8s/services/authentik/extra/blueprints/events-vault-write.yaml?ref_type=heads) is a an example that does that but for providers instead of outposts, and pushes a secret to vault instead of working with ingresses.

Otherwise, you can open a feature request [here](https://github.com/goauthentik/authentik/issues/new/choose).
