### ISSUE TITLE
Version discrepencies

### ISSUE THREAD

**Issue by disconn3ct** [goauthentik/helm#76]
The readme says 
![image](https://user-images.githubusercontent.com/397465/175309746-38e0b515-3d7f-4974-844e-7fc8fe7435da.png) 
(appversion 2022.6.1) but the chart.yaml is `appVersion: 2022.6.2`

Is there a reason to track the chart version independently, as opposed to just automating releases for each upstream?

**Comment by BeryJu** [comment]
The reason the chart is currently released separately is because well, multi-repo release management is quite painful, hence there are quite a few steps that currently need to be done:
- authentik bumpversion on version branch
- publish github release
- merge version branch back into master
- merge PR for web API update
- bump version in version repo
- bump version here for helm chart
- bump version in appliances repo

**Comment by disconn3ct** [comment]
Currently it claims 2021.6.1, while installing 2021.6.2, despite release of 2021.6.3. That is not just "multi-repo release", that is a bug. At a bare minimum, it should install the appversion it reports. (From an architecture perspective, using "separate but equal" revisions is asking for trouble just like this. The chart should be independently versioned.)

Relatedly, there is no need for hand-coding the image tag (another place for drift to occur.) Defaulting to `{{ .Chart.AppVersion }}` resolves that and makes sure it installs what it claims.
